### ISSUE TITLE
Demo Link video, Broken link

### ISSUE THREAD

**Issue by Nkuta** [frankeno/swipe-gestures-unity#1]
The demo video link refers to a video that is no longer available on YouTube.
![image](https://user-images.githubusercontent.com/99332119/215277403-b78d0cdd-1805-4d52-8369-49ef20865f4b.png)

**Comment by frankeno** [comment]
Sorry, I’ll make a new one

**Comment by frankeno** [comment]
Here's the video: https://www.youtube.com/watch?v=J2moIV7clAc

**Comment by Nkuta** [comment]
Thank you for the working video link
